CREATE TABLE CALC_OPERACIONES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERACION VARCHAR2(10),
    NUM1 NUMBER,
    NUM2 NUMBER,
    RESULTADO NUMBER,
    CREATED_AT DATE DEFAULT SYSDATE
);

COMMIT;